name: Send Daily Maxim Email

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - run: pip install supabase boto3
      
      - name: Run Python Script
        run: python send_daily_maxims.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
          AWS_DEFAULT_REGION: 'us-east-2'
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
